const PLL = `Aa: "x R' U R' D2 R U' R' D2 R2"
Ab: "x R2 D2 R U R' D2 R U' R"
E: "x' R U' R' D R U R' D' R U R' D R U' R' D'"
F: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R"
Ga: "R2 U R' U R' U' R U' R2 D U' R' U R D'"
Gb: "R' U' R U D' R2 U R' U R U' R U' R2 D"
Gc: "R2 U' R U' R U R' U R2 D' U R U' R' D"
Gd: "R U R' U' D R2 U' R U' R' U R' U R2 D'"
H: "M2 U' M2 U2 M2 U' M2"
Ja: "x R2 F R F' R U2 r' U r U2"
Jb: "R U R' F' R U R' U' R' F R2 U' R'"
Na: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'"
Nb: "r' D' F r U' r' F' D r2 U r' U' r' F r F'"
Ra: "R U' R' U' R U R D R' U' R D' R' U2 R'"
Rb: "R' U2 R U2 R' F R U R' U' R' F' R2"
T: "R U R' U' R' F R2 U' R' U' R U R' F'"
Ua: "M2 U M U2 M' U M2"
Ub: "M2 U' M U2 M' U' M2"
V: "R' U R' U' y R' F' R2 U' R' U R' F R F"
Y: "F R U' R' U' R U R' F' R U R' U' R' F R F'"
Z: "M' U' M2 U' M2 U' M' U2 M2"`;

const OLL = `OLL 1: "R U2 R2 F R F' U2 R' F R F'"
OLL 2: "R U' R2 D' r U r' D R2 U R'"
OLL 3: "R' F2 R2 U2 R' F R U2 R2 F2 R"
OLL 4: "R' F2 R2 U2 R' F' R U2 R2 F2 R"
OLL 5: "r' U2 R U R' U r"
OLL 6: "r U2 R' U' R U' r'"
OLL 7: "r U R' U R U2 r'"
OLL 8: "l' U' L U' L' U2 l"
OLL 9: "R U R' U' R' F R2 U R' U' F'"
OLL 10: "R U R' U R' F R F' R U2 R'"
OLL 11: "r' R2 U R' U R U2 R' U M'"
OLL 12: "M' R' U' R U' R' U2 R U' M"
OLL 13: "F U R U' R2 F' R U R U' R'"
OLL 14: "R' F R U R' F' R F U' F'"
OLL 15: "r' U' r R' U' R U r' U r"
OLL 16: "r U r' R U R' U' r U' r'"
OLL 17: "R U R' U R' F R F' U2 R' F R F'"
OLL 18: "R U2 R2 F R F' U2 M' U R U' r'"
OLL 19: " S' R U R' S U' R' F R F'"
OLL 20: "S' R U R' S U' M' U R U' r'"
OLL 21: "R U R' U R U' R' U R U2 R'"
OLL 22: "R U2 R2 U' R2 U' R2 U2 R"
OLL 23: "R2 D R' U2 R D' R' U2 R'"
OLL 24: "r U R' U' r' F R F'"
OLL 25: "F' r U R' U' r' F R"
OLL 26: "R U2 R' U' R U' R'"
OLL 27: "R U R' U R U2 R'"
OLL 28: "r U R' U' M U R U' R'"
OLL 29: "r2 D' r U r' D r2 U' r' U' r"
OLL 30: "r' D' r U' r' D r2 U' r' U r U r'"
OLL 31: "R' U' F U R U' R' F' R"
OLL 32: "S R U R' U' R' F R f'"
OLL 33: "R U R' U' R' F R F'"
OLL 34: "f R f' U' r' U' R U M'"
OLL 35: "R U2 R2 F R F' R U2 R'"
OLL 36: "L' U' L U' L' U L U L F' L' F"
OLL 37: "F R U' R' U' R U R' F'"
OLL 38: "R U R' U R U' R' U' R' F R F'"
OLL 39: "f' r U r' U' r' F r S"
OLL 40: "R' F R U R' U' F' U R"
OLL 41: "R U R' U R U2 R' F R U R' U' F'"
OLL 42: "R' U' R U' R' U2 R F R U R' U' F'"
OLL 43: "R' U' F' U F R"
OLL 44: "F U R U' R' F'"
OLL 45: "F R U R' U' F'"
OLL 46: "R' U' R' F R F' U R"
OLL 47: "F' L' U' L U L' U' L U F"
OLL 48: "F R U R' U' R U R' U' F'"
OLL 49: "r U' r2 U r2 U r2 U' r"
OLL 50: "r' U r2 U' r2 U' r2 U r'"
OLL 51: "F U R U' R' U R U' R' F'"
OLL 52: "R' F' U' F U' R U R' U R"
OLL 53: "r' U' R U' R' U R U' R' U2 r"
OLL 54: "r U R' U R U' R' U R U2 r'"
OLL 55: "R' F U R U' R2 F' R2 U R' U' R"
OLL 56: "r U r' U R U' R' M' U R U2 r'"
OLL 57: "R U R' U' M' U R U' r'"`;

export { PLL, OLL };
