const PLL = `Aa: "x R' U R' D2 R U' R' D2 R2"
Ab: "x R2 D2 R U R' D2 R U' R"
E: "x' R U' R' D R U R' D' R U R' D R U' R' D'"
F: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R"
Ga: "R2 U R' U R' U' R U' R2 D U' R' U R D'"
Gb: "R' U' R U D' R2 U R' U R U' R U' R2 D"
Gc: "R2 U' R U' R U R' U R2 D' U R U' R' D"
Gd: "R U R' U' D R2 U' R U' R' U R' U R2 D'"
H: "M2 U' M2 U2 M2 U' M2"
Ja: "x R2 F R F' R U2 r' U r U2"
Jb: "R U R' F' R U R' U' R' F R2 U' R'"
Na: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'"
Nb: "r' D' F r U' r' F' D r2 U r' U' r' F r F'"
Ra: "R U' R' U' R U R D R' U' R D' R' U2 R'"
Rb: "R' U2 R U2 R' F R U R' U' R' F' R2"
T: "R U R' U' R' F R2 U' R' U' R U R' F'"
Ua: "M2 U M U2 M' U M2"
Ub: "M2 U' M U2 M' U' M2"
V: "R' U R' U' y R' F' R2 U' R' U R' F R F"
Y: "F R U' R' U' R U R' F' R U R' U' R' F R F'"
Z: "M' U' M2 U' M2 U' M' U2 M2"`;

const OLL = `1: "R U2 R2 F R F' U2 R' F R F'"
2: "R U' R2 D' r U r' D R2 U R'"
3: "R' F2 R2 U2 R' F R U2 R2 F2 R"
4: "R' F2 R2 U2 R' F' R U2 R2 F2 R"
5: "r' U2 R U R' U r"
6: "r U2 R' U' R U' r'"
7: "r U R' U R U2 r'"
8: "l' U' L U' L' U2 l"
9: "R U R' U' R' F R2 U R' U' F'"
10: "R U R' U R' F R F' R U2 R'"
11: "r' R2 U R' U R U2 R' U M'"
12: "M' R' U' R U' R' U2 R U' M"
13: "F U R U' R2 F' R U R U' R'"
14: "R' F R U R' F' R F U' F'"
15: "r' U' r R' U' R U r' U r"
16: "r U r' R U R' U' r U' r'"
17: "R U R' U R' F R F' U2 R' F R F'"
18: "R U2 R2 F R F' U2 M' U R U' r'"
19: " S' R U R' S U' R' F R F'"
20: "S' R U R' S U' M' U R U' r'"
21: "R U R' U R U' R' U R U2 R'"
22: "R U2 R2 U' R2 U' R2 U2 R"
23: "R2 D R' U2 R D' R' U2 R'"
24: "r U R' U' r' F R F'"
25: "F' r U R' U' r' F R"
26: "R U2 R' U' R U' R'"
27: "R U R' U R U2 R'"
28: "r U R' U' M U R U' R'"
29: "r2 D' r U r' D r2 U' r' U' r"
30: "r' D' r U' r' D r2 U' r' U r U r'"
31: "R' U' F U R U' R' F' R"
32: "S R U R' U' R' F R f'"
33: "R U R' U' R' F R F'"
34: "f R f' U' r' U' R U M'"
35: "R U2 R2 F R F' R U2 R'"
36: "L' U' L U' L' U L U L F' L' F"
37: "F R U' R' U' R U R' F'"
38: "R U R' U R U' R' U' R' F R F'"
39: "f' r U r' U' r' F r S"
40: "R' F R U R' U' F' U R"
41: "R U R' U R U2 R' F R U R' U' F'"
42: "R' U' R U' R' U2 R F R U R' U' F'"
43: "R' U' F' U F R"
44: "F U R U' R' F'"
45: "F R U R' U' F'"
46: "R' U' R' F R F' U R"
47: "F' L' U' L U L' U' L U F"
48: "F R U R' U' R U R' U' F'"
49: "r U' r2 U r2 U r2 U' r"
50: "r' U r2 U' r2 U' r2 U r'"
51: "F U R U' R' U R U' R' F'"
52: "R' F' U' F U' R U R' U R"
53: "r' U' R U' R' U R U' R' U2 r"
54: "r U R' U R U' R' U R U2 r'"
55: "R' F U R U' R2 F' R2 U R' U' R"
56: "r U r' U R U' R' M' U R U2 r'"
57: "R U R' U' M' U R U' r'"`;

const PBL = `Adj: "R U R' F' R U R' U' R' F R2 U' R'"
Opp: "R U' R' U' F2 U' R U R' U F2"
Opp/Opp: "R2 F2 R2"
Adj/Adj: "R2 U' B2 U2 R2 U' R2"
Adj/Opp: "R U' R F2 R' U R'"
Opp/Adj: "R2 U R2 U' R2 U R2 U' R2"`;

const CLL = `AS1: "R U2 R' U' R U' R'"
AS2: "R U2 R' F R' F' R U' R U' R'"
AS3: "F' L F L' U2 L' U2 L"
AS4: "R' F R F' R U R'"
AS5: "R U2 R' U2 R' F R F'"
AS6: "L' U' L U L F' L' F L' U' L U' L' U2 L"
H1: "F R2 U' R2 U' R2 U R2 F'"
H2: "R U R' U R U R' F R' F' R"
H3: "F R U R' U' R U R' U' R U R' U' F'"
H4: "R2 U2 R' U2 R2"
L1: "R U2 R' F' R U2 R' U R' F2 R"
L2: "R U2 R2 F2 R U R' F2 R F'"
L3: "R' U R' U2 R U' R' U R U' R2"
L4: "R U2 R2 F R F' R U2 R'"
L5: "F R' F' R U R U' R'"
L6: "F' R U R' U' R' F R"
P1: "F R' F' R U2 R U' R' U R U2 R'"
P2: "R U2 R' U' R U R' U2 R' F R F'"
P3: "F R2 U' R2 U R2 U R2 F'"
P4: "R' F R F' R U' R' U' R U' R'"
P5: "R' U' R' F R F' R U' R' U2 R"
P6: "R U' R2 U R2 U R2 U' R"
S1: "L' U2 L U2 L F' L' F"
S2: "R U R' U' R' F R F' R U R' U R U2 R'"
S3: "R U' R' F R' F' R"
S4: "F R' F' R U2 R U2 R'"
S5: "R U R' U R' F R F' R U2 R'"
S6: "R U R' U R U2 R'"
T1:  "R U R' U' R' F R F'"
T2: "L' U' L U L F' L' F"
T3: "F U' R U2 R' U' F2 R U R'"
T4: "R' U R U2 R2 F' R U' R' F2 R2"
T5: "F R U R' U' R U' R' U' R U R' F'"
T6: "R' U R U2 R2 F R F' R"
U1: "F R U R' U' F'"
U2: "R2 F2 R U R' F R2 U2 R' U' R"
U3: "F R U R' U2 F' R U' R' F"
U4: "F R' F' R U' R U' R' U2 R U' R'"
U5: "R U' R2 F R F' R U R' U' R U R'"
U6: "R' U R' F R F' R U2 R' U R"`;

export { PLL, OLL, PBL, CLL };
